/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205758;

import java.util.Scanner;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class QuizTest {
    @Test
    public void testAnswer(){
        Scanner scan = new Scanner(System.in);
        String a = scan.nextLine();
        
    }
}